name: Continuous Integration and Continuous Deployment
run-name: ${{ github.actor }} submitted a CI CD Action
on:
  push:
    branches: 
      - main
      - milestone6

jobs:
  Explore-GitHub-Actions:
    if: contains(github.event.head_commit.message, 'run-')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment ${{ github.event.head_commit.message }}"
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker # --quiet #authenticate to gcr
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build Deployment Container 
        run: |-
          cd ${{ github.workspace }}/src/deployment/
          docker build -t fakenews-deployment -f Dockerfile .
      - name: Run Deploy App
        if: contains(github.event.head_commit.message, 'run-deploy-app')
        run: |-
          docker run --rm --name fakenews-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.ssh:/home/app/.ssh \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            --volume $GITHUB_WORKSPACE:/workspace \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            --env GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-398714 \
            -e GCP_ZONE=us-central1-a \
            fakenews-deployment sh deploy-setup-webserver.yml
      - name: Run Data Processor Pipeline
        if: contains(github.event.head_commit.message, 'run-data-processor')
        run: |-
          docker run --rm --name fakenews-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/training:/training \
            -v ${{ github.workspace }}/src/preprocessing:/preprocessing \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            --mount type=bind,source=$WANDB_KEY,target=/secrets/wandb_key.txt \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e GOOGLE_WANDB_KEY=/secrets/wandb_key.txt \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-398714 \
            -e GCP_ZONE=us-central1-a \
            -e GCS_BUCKET_NAME=fakenew_classifier_data_bucket \
            -e GCS_SERVICE_ACCOUNT=deployment@ac215-398714.iam.gserviceaccount.com \
            -e GCP_REGION=us-central1 \
            -e GCS_PACKAGE_URI=gs://fakenews-classifier \
            fakenews-deployment sh deploy-setup-containers.yml
      - run: echo "Job's status is ${{ job.status }}."